---
title: "pull tweets"
author: "hoskisson"
date: "2023-04-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rtweet)
library(tidyverse)
library(academictwitteR)
library(jsonlite)
```

```{r}
token = rtweet::create_token(app = "compromise_words",
                             consumer_key = NULL,
                             consumer_secret = NULL,
                             access_token = "1315770860372811776-ov5CEVpi2NiJYm6xhVynCjFLwyFrbF",
                             access_secret = "2MU1iCEMn6irCvDKb22lAplQl44PpeH18oeaVIfA75G6H")
```

```{r}
auth_as(auth)
```


```{r}
# for academictwitteR
set_bearer()
```



```{r}
senator_handles_table <- read.csv("data/senator_handles_table.csv")
handles <- senator_handles_table$senator_handles_list
```

## American Rescue Plan Act of 2021

Read Tweets with app that has Academic status on the Twitter API.
Using package academictwitteR
```{r}
american_rescue_2021_a <- get_all_tweets(
  users = handles[1:46],
  start_tweets = "2021-02-20T00:00:00Z",
  end_tweets = "2021-03-05T00:00:00Z",
  file = "data/raw_tweets/american_rescue_2021/american_rescue_2021a",
  data_path = "data/raw_tweets/american_rescue_2021",
  n = 100000
)

get_all_tweets(
  users = handles[47:92],
  start_tweets = "2021-02-20T00:00:00Z",
  end_tweets = "2021-03-05T00:00:00Z",
  file = "american_rescue_2021b",
  data_path = "data/raw_tweets/american_rescue_2021b",
  n = 100000
)

get_all_tweets(
  users = handles[93:138],
  start_tweets = "2021-02-20T00:00:00Z",
  end_tweets = "2021-03-05T00:00:00Z",
  file = "data/raw_tweets/american_rescue_2021c/american_rescue_2021c.RDS",
  data_path = "data/raw_tweets/american_rescue_2021c",
  n = 100000
)

get_all_tweets(
  users = handles[139:184],
  start_tweets = "2021-02-20T00:00:00Z",
  end_tweets = "2021-03-05T00:00:00Z",
  file = "data/raw_tweets/american_rescue_2021d/american_rescue_2021d.RDS",
  data_path = "data/raw_tweets/american_rescue_2021d",
  n = 100000
)
```

```{r}
american_rescue_2021a_users1 <- fromJSON("data/raw_tweets/american_rescue_2021a/users_1362914870451195904.json")[[1]]
american_rescue_2021a_users2 <- fromJSON("data/raw_tweets/american_rescue_2021a/users_1363247060879695874.json")[[1]]
american_rescue_2021a_users3 <- fromJSON("data/raw_tweets/american_rescue_2021a/users_1364945375430344710.json")[[1]]
american_rescue_2021a_users4 <- fromJSON("data/raw_tweets/american_rescue_2021a/users_1366517877155725320.json")[[1]]

american_rescue_2021b_users1 <- fromJSON("data/raw_tweets/american_rescue_2021b/users_1362916020256669699.json")[[1]]
american_rescue_2021b_users2 <- fromJSON("data/raw_tweets/american_rescue_2021b/users_1364309472651464704.json")[[1]]
american_rescue_2021b_users3 <- fromJSON("data/raw_tweets/american_rescue_2021b/users_1365327974556442625.json")[[1]]
american_rescue_2021b_users4 <- fromJSON("data/raw_tweets/american_rescue_2021b/users_1366810294434095106.json")[[1]]

american_rescue_2021c_users1 <- fromJSON("data/raw_tweets/american_rescue_2021c/users_1362920895019442178.json")[[1]]
american_rescue_2021c_users2 <- fromJSON("data/raw_tweets/american_rescue_2021c/users_1364652461152210949.json")[[1]]
american_rescue_2021c_users3 <- fromJSON("data/raw_tweets/american_rescue_2021c/users_1366402818039513088.json")[[1]]

american_rescue_2021d_users1 <- fromJSON("data/raw_tweets/american_rescue_2021d/users_1362916888456658947.json")[[1]]
american_rescue_2021d_users2 <- fromJSON("data/raw_tweets/american_rescue_2021d/users_1364289288477753346.json")[[1]]
american_rescue_2021d_users3 <- fromJSON("data/raw_tweets/american_rescue_2021d/users_1365337881066287107.json")[[1]]
american_rescue_2021d_users4 <- fromJSON("data/raw_tweets/american_rescue_2021d/users_1366810813554692097.json")[[1]]

american_rescue_2021_users <- bind_rows(
  american_rescue_2021a_users1,
  american_rescue_2021a_users2,
  american_rescue_2021a_users3,
  american_rescue_2021a_users4,
  american_rescue_2021b_users1,
  american_rescue_2021b_users2,
  american_rescue_2021b_users3,
  american_rescue_2021b_users4,
  american_rescue_2021c_users1,
  american_rescue_2021c_users2,
  american_rescue_2021c_users3,
  american_rescue_2021d_users1,
  american_rescue_2021d_users2,
  american_rescue_2021d_users3,
  american_rescue_2021d_users4
) %>%
  select(id, username) %>%
  distinct(.keep_all = TRUE)
```

```{r}
american_rescue_2021a <- readRDS("data/raw_tweets/american_rescue_2021a/american_rescue_2021a")
american_rescue_2021b <- readRDS("data/raw_tweets/american_rescue_2021b/american_rescue_2021b")
american_rescue_2021c <- readRDS("data/raw_tweets/american_rescue_2021c/american_rescue_2021c.RDS")
american_rescue_2021d <- readRDS("data/raw_tweets/american_rescue_2021d/american_rescue_2021d.RDS")

american_rescue_2021_tweets <- bind_rows(
  american_rescue_2021a,
  american_rescue_2021b,
  american_rescue_2021c,
  american_rescue_2021d
)

american_rescue_2021_tweets <- american_rescue_2021_tweets %>%
  left_join(american_rescue_2021_users, by = c("author_id" = "id"))

# remove columns that are lists and dataframes
american_rescue_2021_tweets <- american_rescue_2021_tweets %>%
  select(-c(public_metrics, edit_history_tweet_ids, entities, referenced_tweets, attachments, geo))

american_rescue_2021_tweets$id_str <- american_rescue_2021_tweets$id
saveRDS(american_rescue_2021_tweets, "data/raw_tweets/american_rescue_2021_corrected.rds")
```

The rest of this section is old data that I used and accidently queried 2022
instead of 2021.
```{r}
american_rescue_2021 <- get_timeline(
  user=handles,
  since_id = c("1495486916082425857"),
  max_id = c("1500957088738160643")
)

american_rescue_2021_users <- users_data(american_rescue_2021)
```

```{r}
# remove columns that are lists because they will cause errors
american_rescue_2021_selected <- american_rescue_2021 %>%
  select(-c(geo, coordinates, entities, place, possibly_sensitive, retweeted_status, quoted_status, quoted_status_permalink, withheld_in_countries))

write.csv(american_rescue_2021_selected, "data/raw_tweets/american_rescue_2021.csv", row.names = FALSE)

american_rescue_2021_users_selected <- american_rescue_2021_users %>%
  select(-c(derived, withheld_in_countries, entities))

write.csv(american_rescue_2021_users_selected, "data/raw_tweets/american_rescue_2021_users.csv", row.names = FALSE)
```

## Respect for marriage act 2022
```{r}
respect_for_marriage <- get_timeline(
  user=handles,
  max_id = c("1598011580016304128"),
  since_id = c("1592524893316579329")
)

respect_for_marriage_users <- users_data(respect_for_marriage)
```

```{r}
respect_for_marriage %>%
  select(-c(geo, coordinates, entities, place, possibly_sensitive, retweeted_status, quoted_status, quoted_status_permalink, withheld_in_countries)) %>%
  write.csv("data/raw_tweets/respect_for_marriage.csv")

respect_for_marriage_users %>%
  select(-c(derived, withheld_in_countries, entities)) %>%
  write.csv("data/raw_tweets/respect_for_marriage_users.csv")
```

## Inflation Reduction Act 2022
```{r}
inflation_reduction <- get_timeline(
  user=handles,
  since_id = c("1551208949382258690"),
  max_id = c("1556772322832310272")
)

inflation_reduction_users <- users_data(inflation_reduction)
```

```{r}
inflation_reduction %>%
  select(-c(geo, coordinates, entities, place, possibly_sensitive, retweeted_status, quoted_status, quoted_status_permalink, withheld_in_countries)) %>%
  write.csv("data/raw_tweets/inflation_reduction.csv")

inflation_reduction_users %>%
  select(-c(derived, withheld_in_countries, entities)) %>%
  write.csv("data/raw_tweets/inflation_reduction_users.csv")
```

## Bipartisan Safer Communities Act of 2022

```{r}
safer_communities <- get_timeline(
  user=handles,
  since_id = c("1534892587399643137"),
  max_id = c("1540421395804463107")
)

safer_communities_users <- users_data(safer_communities)
```

```{r}
safer_communities %>%
  select(-c(geo, coordinates, entities, place, possibly_sensitive, retweeted_status, quoted_status, quoted_status_permalink, withheld_in_countries)) %>%
  write.csv("data/raw_tweets/safer_communities.csv")

safer_communities_users %>%
  select(-c(derived, withheld_in_countries, entities)) %>%
  write.csv("data/raw_tweets/safer_communities_users.csv")
```

## Infrastructure Investment and Jobs Act of 2021
```{r}
infrastructure_investment <- get_timeline(
  user=handles,
  since_id = c("1420021866262040577"),
  max_id = c("1425616774146543618")
)

infrastructure_investment_users <- users_data(infrastructure_investment)
```

```{r}
infrastructure_investment %>%
  select(-c(geo, coordinates, entities, place, possibly_sensitive, retweeted_status, quoted_status, quoted_status_permalink, withheld_in_countries)) %>%
  write.csv("data/raw_tweets/infrastructure_investment.csv")

infrastructure_investment_users %>%
  select(-c(derived, withheld_in_countries, entities)) %>%
  write.csv("data/raw_tweets/infrastructure_users.csv")
```

